Name: Notes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  page: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/configure-pages@v4

      - name: Upload static files
        uses: peaceiris/actions-gh-pages@v4
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        